---

- name: prepare system
  ansible.builtin.import_tasks: preparation.yml
  when: skip_preparation == false
    
- name: Check subuid & subgid
  ansible.builtin.import_tasks: check_subid.yml
  when: skip_preparation == false
